### ISSUE TITLE
please add debug output off option to config

### ISSUE THREAD

**Issue by elpinguinofrio** [AzumattDev/AzuCraftyBoxes#10]
currently Player.log isn't readable because this mode writes 70% of output, please make debug optional.

**Comment by AzumattDev** [comment]
It already is. Debug logging is only printed if you have it turned on or Unity logs are printing it. Read your BepInEx/LogOutput.log for all mod related things as well as vanilla. All log configurations are in the BepInEx.cfg

**Comment by elpinguinofrio** [comment]
the request is to be able to turn off logs for mod individually, because this is example of player.log, there's something is definitely off if out of 14 mods the most of output by far is coming from one mod only
<img width="904" alt="image" src="https://github.com/user-attachments/assets/0ad9fa01-6816-421f-bb40-a26747208ff1">
it basically prints the whole 254 lines yaml file to console for some reason, and later huge output every time crafting is used. It would be great if you consider to add ShowDebugLogs parameter to AzuCraftyBoxes.cfg, like for example quick_stack_store does it. I'm not sure if there's other simple way to turn it off, but I couldn't find it in the .cfg at the moment 
![image](https://github.com/user-attachments/assets/bac1130d-a8e8-42a2-adbe-65a97f8830c1)
thanks for consideration!

**Comment by AzumattDev** [comment]
You should be reading BepInEx LogOutput and making sure debug logging is not printed via that configuration option. I do not need to add it individually to my mod. It's the entire reason for BepInEx logging having those configuration options.

**Comment by elpinguinofrio** [comment]
@AzumattDev, I checked the BeppInEx.cfg and BeppInEx/LogOutput.log as you suggested. However, I couldn’t find a setting to turn off debug logging specifically for individual mods. It’s still cluttering the Player.log with about +70% mod-related outputs. Could you advise if there’s a way to selectively disable these outputs? It would help in keeping the log readable. Thanks!

**Comment by AzumattDev** [comment]
Well, as stated, debug logging is a configuration in the BepInEx area. You shouldn't be reading the Player.log if you want information on mods. You should be reading the BepInEx/LogOutput.log file. It's not individual mod configurable. It's global for all mods, hence why the logging is sent through that system. The BepInEx log file contains all relevant information from vanilla and mods. There is almost zero reason to read the Player.log.

**Comment by elpinguinofrio** [comment]
You keep answering different question. There's literally link to open player.log from main menu of the game. It intended to be read by users see if something is very wrong with some mods that keep crashing for example. So why out of all popular mods your one if the most verbose, so much so it writes more than all other combined? don't you think you might be doing something wrong here?

**Comment by AzumattDev** [comment]
I'm telling you where to find your modded information and the log that should be read. My answer is no. I'm not doing anything wrong as I'm using the modding framework's logging system. You should read your modded logs when playing modded. Not the vanilla logs.
