### ISSUE TITLE
[Compatibility Issue] Crafting from Backpack

### ISSUE THREAD

**Issue by ryanburst** [AzumattDev/AzuCraftyBoxes#2]
When using the [Backpack Mod](https://thunderstore.io/c/valheim/p/Smoothbrain/Backpacks/) by Smoothbrain, the contents of the backpack are not included in available materials for crafting. I'm not sure if it's an issue with Backpacks or with this mod, but I'll open a ticket in both.

[Adventure Backpacks](https://thunderstore.io/c/valheim/p/Vapok/AdventureBackpacks/) by Vapok is compatible, but does not work with the [Extended Player Inventory](https://thunderstore.io/c/valheim/p/Azumatt/AzuExtendedPlayerInventory/) mod in regards to using a `Backpack` slot instead of `Back`. Backpack is also required for [Bows Before Hoes](https://thunderstore.io/c/valheim/p/Azumatt/BowsBeforeHoes/) so I would rather not switch to Adventure Backpacks just to get backpack contents recognized for crafting.

**Comment by AzumattDev** [comment]
This is now possible and was done in db308045aeaa459a74dfc966b74841390dc89271
