### ISSUE TITLE
[Feature request] Option to disable remote fetch for cooking station

### ISSUE THREAD

**Issue by AlanDrake** [AzumattDev/AzuCraftyBoxes#3]
It would be nice being able to exclude cooking stations from the mechanic, so you don't end up using random meats that you were keeping for other recipes.

**Comment by AzumattDev** [comment]
Already possible. Configure the yaml file.

**Comment by AlanDrake** [comment]
How emabrrassing, I had completely overlooked the yaml existed...
Thank you.
